### ISSUE TITLE
Simplify virtual environment usage on relay side

### ISSUE THREAD

**Issue by csebille** [BROADSoftware/HADeploy#2]
Hi Serge,

I've started to use hadeploy and it indeed simplifies Hadoop projects deployment.
I succeeded in using it but there still is a point concerning the relay.
My context : controller : Centos 6.5, relay : Centos 7.6, HDP 3.0.1
Currently, I have all the necessary rights on the controller side to run the project. 
On the other side, on my hdfs relay, I only have limited rights and some actions as installing globally new python's modules or installing rpms with yum are forbidden.
As a workaround, I have set up a virtual env thanks to venv-pack containing request and request-kerberos already installed. 
I have manually linked all native modules to get a fully functional environment.

My problem is that in file _HADeploy/lib/hadeploy/plugins/hdfs/roles/hdfs_modules/tasks/main.yml_ there is this step which needs yum and fails :

```
- name: Install python-requests and python-requests-kerberos for hdfs_xxxxx ansibles modules (RedHat)
  yum: name=python-requests,python-requests-kerberos state=present
  when: ansible_os_family == 'RedHat'
```

If I comment this task, it works well as the required modules have already been provided in the virtual env.
If I tag this task as "virtual_env_not_provided" and make ansible skip this very tag, it still works 

```
- name: Install python-requests and python-requests-kerberos for hdfs_xxxxx ansibles modules (RedHat)
  yum: name=python-requests,python-requests-kerberos state=present
  when: ansible_os_family == 'RedHat'
  tags: virtual_env_not_provided

```

`bash -c "cd $WF; ansible-playbook ${VAULT_PASSWORD} ${VERBOSE} ${ACTION}.yml  --skip-tags \"virtual_env_not_provided\""`

So my request is an enhancement about tagging these tasks that require root rights and the capability to set extra parameters in the command line tool directly appended at the end of the ansible-playbook command.

eg :
```
#After having shifted all the hadeploy parameters, consider sending the remaining one to ansible-playbook
bash -c "cd $WF; ansible-playbook ${VAULT_PASSWORD} ${VERBOSE} ${ACTION}.yml $@"
```
So I could directly use 

`hadeploy --src app.yml --action deploy --skip-tags \"virtual_env_not_provided\""
`
Best regards,

Christophe

**Comment by SergeAlexandre** [comment]
Hi Christophe,

Thanks for using HADeploy

After looking at the issue you raised up, I have implemented an alternative solution.

I have added a `privileged` flag on the `host` definition. When set to 'no', then all yum operation on such host are skipped.

If you use an Ansible provided inventory, you can set this flag using the `host_overrides` item. For exemple to apply this flag to all hosts:

```
host_overrides:
- name: all
  privileged: no
```
I have also added another flag: `python_interpreter`. It will set the `ansible_python_interpreter` Ansible variable. 

You can set this variable to a virtualenv of your own, with 'requests' and 'requests-kerberos' packages already installed. For exemple:

```
host_overrides:
  name: edgenode
  ssh_user: deployer
  ssh_private_key_file: /Users/john/.ssh/deployer_id_dsa
  privileged: no
  python_interpreter: /home/deployer/virtualenv1/bin/python  

hdfs_relay: 
  host: edgenode
  principal: deployer
  local_keytab_path: ./deployer.keytab

```
This means all access on host 'edgenode' will be performed under 'deployer' account, using its private key (Located on the controller node). And the '/home/deployer/virtualenv1/bin/python' interpreter will be used on the target host (edgenode).

This host can then be used as the HDFS relay. And, if kerberos is enabled on the cluster, a principal and keytab must be provided for HDFS access.

I plan to include these new configuration parameters in the next release. In the mid time, you can test/use them by installing HADeploy directly from [source Git repository](https://www.hadeploy.com/installation/#install-from-source-git-repository), using the branch 'master'

Let me know if this works for you.

Best regards

Serge

**Comment by csebille** [comment]
Hi Serge,
  Ok, I'll test this asap and let you know how it went.
Christophe

**Comment by csebille** [comment]
Hi Serge,
  It took me a bit of time to come back on this subject.

  It works like a charm !

Best Regards,

Christophe
